#!/bin/bash
# Filename:    build_demo_site.sh
# Description: Build the GitHub Pages demo showcase into docs/ from the
#              bundle's pages. The hosted copy forces demo mode for every
#              visitor via its config.js, so all entry points work without
#              an Indigo server. Run from the repo root, then commit docs/.
# Author:      CliveS & Claude Fable 5
# Date:        11-06-2026
# Version:     1.0
set -euo pipefail
cd "$(dirname "$0")/.."

PAGES="Dashboards.indigoPlugin/Contents/Resources/static/pages"
DOCS="docs"

rm -rf "$DOCS"
mkdir -p "$DOCS"

# Pages, shared JS, manifest, icons + the demo fixtures.
cp "$PAGES"/*.html "$PAGES"/*.js "$PAGES"/manifest.json "$PAGES"/*.png "$DOCS/" 2>/dev/null || true
cp -R "$PAGES/demo-data" "$DOCS/demo-data"

# Hosted config.js: forces demo mode for every visitor (config.js loads
# before dashboards-auth.js on every page, so this covers all entry points)
# and provides a placeholder camera setup so cameras.html renders.
cat > "$DOCS/config.js" << 'EOF'
// GitHub Pages demo build — generated by tools/build_demo_site.sh.
sessionStorage.setItem("dash_demo", "1");
window.INDIGO_CONFIG = {};
window.INDIGO_CONFIG_SOURCE = "demo build";
window.CAMERA_CONFIG = {
    "hosts": ["192.0.2.1", "192.0.2.2", "192.0.2.3", "192.0.2.4"],
    "names": {"192.0.2.1": "Front Door", "192.0.2.2": "Drive",
              "192.0.2.3": "Garage", "192.0.2.4": "Back Garden"},
    "slugs": {"192.0.2.1": "front_door", "192.0.2.2": "drive",
              "192.0.2.3": "garage", "192.0.2.4": "back_garden"},
    "imagePattern": "demo-cam.svg",
    "pollSeconds": 9999, "mjpegPort": 0, "mjpegPath": "",
    "go2rtcPort": 0, "livePoolSize": 0,
    "mainCameras": ["192.0.2.1", "192.0.2.2", "192.0.2.3", "192.0.2.4"],
    "swapOutHost": ""
};
EOF

# Camera placeholder image.
cat > "$DOCS/demo-cam.svg" << 'EOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 360">
  <rect width="640" height="360" fill="#1c1c2e"/>
  <text x="320" y="170" fill="#8884d8" font-family="-apple-system,sans-serif"
        font-size="28" font-weight="600" text-anchor="middle">Camera feed</text>
  <text x="320" y="205" fill="#666" font-family="-apple-system,sans-serif"
        font-size="16" text-anchor="middle">(live MJPEG on a real install)</text>
</svg>
EOF

echo "Demo site built into $DOCS/ ($(ls "$DOCS" | wc -l | tr -d ' ') files)."
echo "Entry point once published: <pages-url>/demo.html (or any page — demo is forced)."
