#!/bin/bash
# Filename:    build_demo_site.sh
# Description: Build the GitHub Pages demo showcase into docs/demo/ from the
#              bundle's pages. The hosted copy forces demo mode for every
#              visitor via its config.js, so all entry points work without
#              an Indigo server. Run from the repo root, then commit docs/demo/.
#              docs/ itself is the documentation site (Jekyll, GitHub Pages).
#              The demo pages carry no front matter, so Jekyll copies them
#              through untouched. Republished in 3.39.0 at <pages>/demo/.
#              tests/test_demo_site.py fails when docs/demo/ falls behind the
#              bundle, so run this after changing any page.
# Author:      CliveS & Claude Fable 5; Claude Fable 5.1 (1.1); Claude Opus 5.5 (1.2)
# Date:        11-06-2026 (1.1: 11-09-2026, 1.2: 23-09-2026)
# Version:     1.2 (stylesheets were never copied, so every page lost its look;
#              the MJPEG keys went with MJPEG)
set -euo pipefail
cd "$(dirname "$0")/.."

PAGES="Dashboards.indigoPlugin/Contents/Resources/static/pages"
DOCS="docs/demo"

rm -rf "$DOCS"
mkdir -p "$DOCS"

# Pages, shared JS, manifest, icons + the demo fixtures.
cp "$PAGES"/*.html "$PAGES"/*.js "$PAGES"/*.css "$PAGES"/manifest.json "$PAGES"/*.png "$DOCS/"
cp -R "$PAGES/demo-data" "$DOCS/demo-data"
# The files the plugin writes beside the pages on a real install.
cp "$PAGES/demo-data/rooms.json" "$PAGES/demo-data/scenes.json" "$PAGES/demo-data/weather.json" "$DOCS/"

# Hosted config.js: forces demo mode for every visitor (config.js loads
# before dashboards-auth.js on every page, so this covers all entry points)
# and provides a placeholder camera setup so cameras.html renders.
cat > "$DOCS/config.js" << 'EOF'
// GitHub Pages demo build — generated by tools/build_demo_site.sh.
sessionStorage.setItem("dash_demo", "1");
// Every id below is a device in demo-data/devices.json.
window.INDIGO_CONFIG = {
    "siteName": "Demo House",
    "sigenDeviceId": 1563154425,
    "sigenAvailable": true,
    "heatingControls": true,
    "carbon": true,
    "scripts": {"presence": true, "laundry": true},
    "favourites": [
        {"type": "door", "id": 651379270, "label": "Front Door", "lockId": 1835630858},
        {"type": "device", "id": 1188091315, "label": "Conservatory Fan"},
        {"type": "device", "id": 372666822, "label": "Colour Lamp"},
        {"type": "device", "id": 1061201491},
        {"type": "device", "id": 987131616, "label": "Kitchen", "state": "temperature"},
        {"type": "room", "room": "Living Room"},
        {"type": "room", "room": "Kitchen"}
    ],
    "colourPresets": {
        "warm":  {"label": "Warm white", "icon": "cloudsun", "mode": "white", "whiteTemperature": 2700, "brightness": 100},
        "movie": {"label": "Movie", "icon": "film", "mode": "color", "redLevel": 100, "greenLevel": 35, "blueLevel": 8, "brightness": 18}
    }
};
window.INDIGO_CONFIG_SOURCE = "demo build";
window.CAMERA_CONFIG = {
    "hosts": ["192.0.2.1", "192.0.2.2", "192.0.2.3", "192.0.2.4"],
    "names": {"192.0.2.1": "Front Door", "192.0.2.2": "Drive",
              "192.0.2.3": "Garage", "192.0.2.4": "Back Garden"},
    "slugs": {"192.0.2.1": "front_door", "192.0.2.2": "drive",
              "192.0.2.3": "garage", "192.0.2.4": "back_garden"},
    "pollSeconds": 9999, "livePoolSize": 0,
    "mainCameras": ["192.0.2.1", "192.0.2.2", "192.0.2.3", "192.0.2.4"],
    "swapOutHost": ""
};
EOF

# Camera placeholder image. Pages learn where stills are from the cameraStills
# action, which the demo answers from demo-data/api/cameraStills.json.
cat > "$DOCS/demo-cam.svg" << 'EOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 360">
  <rect width="640" height="360" fill="#1c1c2e"/>
  <text x="320" y="170" fill="#8884d8" font-family="-apple-system,sans-serif"
        font-size="28" font-weight="600" text-anchor="middle">Camera feed</text>
  <text x="320" y="205" fill="#666" font-family="-apple-system,sans-serif"
        font-size="16" text-anchor="middle">(live video on a real install)</text>
</svg>
EOF

echo "Demo site built into $DOCS/ ($(ls "$DOCS" | wc -l | tr -d ' ') files)."
echo "Entry point once published: <pages-url>/demo/demo.html (or any page there — demo is forced)."
